'use client'

import './globals.css'
import { FontProvider } from './fontcontext'
import { ThemeProvider } from './themeContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    
  return (
    <html lang="en">
      <ThemeProvider>
      <FontProvider>
      <body>{children}</body>
      </FontProvider>
      </ThemeProvider>
    </html>
  )
}
